version: '3.1'
services:
  mongo:
    image: dolittle/mongodb
    hostname: mongo
    ports:
      - 27017:27017
  
  runtime:
    image: dolittle/runtime:5.0.0-alpha.11
    volumes:
      - ${PWD}/resources.json:/app/.dolittle/resources.json
    ports:
      - 81:81
      - 9700:9700
      - 50052:50052
      - 50053:50053