name: .NET Docker Image CI/CD

env:
  PRERELEASE_BRANCHES: experimental,alpha,beta,rc # Comma separated list of prerelease branch names. 'alpha,rc, ...'
  DOCKER_HUB_REPO: dolittle/runtime # The docker hub repo to push to

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  ci:
    name: Integration
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.context.outputs.should-publish }}
      current-version: ${{ steps.context.outputs.current-version }}
      release-type: ${{ steps.context.outputs.release-type }}
      cascading-release: ${{ steps.context.outputs.cascading-release }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build
    - run: dotnet test
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2
      with:
        prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
    - name: Build Docker image
      uses: docker/build-push-action@v1
      if: ${{ env.DOCKER_HUB_REPO != '' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ env.DOCKER_HUB_REPO }}
        tag_with_sha: true
        push: false

  release:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ needs.ci.outputs.should-publish == 'true' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Increment version
        id: increment-version
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ needs.ci.outputs.current-version }}
          release-type: ${{ needs.ci.outputs.release-type }}
      - name: Create GitHub Release
        uses: dolittle/github-release-action@v1
        with:
          cascading-release: ${{ needs.ci.outputs.cascading-release }}
          version: ${{ steps.increment-version.outputs.next-version }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        if: ${{ env.DOCKER_HUB_REPO != '' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_HUB_REPO }}
          tags: ${{ steps.increment-version.outputs.next-version }}
